LEFT_HAND:
- ACTION_NAME: 张开
  POSITION:
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 握拳
  POSITION:
  - 116
  - 208
  - 0
  - 0
  - 0
  - 0
  - 255
  - 255
  - 255
  - 0
RIGHT_HAND:
- ACTION_NAME: 张开
  POSITION:
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 握拳
  POSITION:
  - 101
  - 60
  - 0
  - 0
  - 0
  - 0
  - 255
  - 255
  - 255
  - 51
- ACTION_NAME: 食指弯曲
  POSITION:
  - 255
  - 255
  - 0
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 中指弯曲
  POSITION:
  - 255
  - 255
  - 255
  - 0
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 无名指弯曲
  POSITION:
  - 255
  - 255
  - 255
  - 255
  - 0
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 小拇指弯曲
  POSITION:
  - 255
  - 255
  - 255
  - 255
  - 255
  - 0
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 拇指侧摆内
  POSITION:
  - 255
  - 0
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 中指无名指弯曲
  POSITION:
  - 255
  - 255
  - 255
  - 0
  - 0
  - 255
  - 255
  - 255
  - 255
  - 255
